# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AuroraPlusBack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='Data',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
